<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="QT-INBG-LT0912" failures="1" tests="1" name="com.QualitestPortalPDFCompare.UnitTests" time="21.218" errors="0" timestamp="27 Sep 2022 10:03:50 GMT" skipped="0">
  <testcase classname="com.QualitestPortalPDFCompare.UnitTests" name="DataCompareTest" time="21.218">
    <failure message="Test case failed due to Multiple Assertion failures
	expected [true] but found [false],
	PDF data differs with 1.5% &amp; for reference &lt;a href=C:\Users\pavan.t\eclipse-workspace\QualidexDemo\Extract_Images\Page_mismatch_3_Page_mismatch_21.png&gt;link&lt;/a&gt; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test case failed due to Multiple Assertion failures
expected [true] but found [false],
PDF data differs with 1.5% & for reference <a href=C:\Users\pavan.t\eclipse-workspace\QualidexDemo\Extract_Images\Page_mismatch_3_Page_mismatch_21.png>link</a> expected [true] but found [false]
at com.qualitestgroup.data_extract_demo.damoregroup.Softassert.assertAll(Softassert.java:55)
at com.QualitestPortalPDFCompare.UnitTests.DataCompareTest(UnitTests.java:272)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- DataCompareTest -->
</testsuite> <!-- com.QualitestPortalPDFCompare.UnitTests -->
